/**
 * BTB Nutrition — food reference database.
 *
 * DATA PROVENANCE
 *  Macro values are per 100 g and were pulled programmatically from the USDA
 *  FoodData Central database (SR Legacy / Foundation Foods), then validated so
 *  each row's returned USDA description matches the intended food. `usdaName`
 *  records the exact source entry and `fdcId` its FoodData Central ID.
 *
 *  One exception: whey protein isolate has no USDA SR entry, so it carries a
 *  typical label value and `fdcId: null`.
 *
 * STYLE CONTRACT (ideas.md — "Blueprint Wall"):
 *  Coach-direct copy. Every note is practical, not promotional.
 *
 * IMPORTANT: this is general nutritional reference information, not dietary
 * advice for any individual.
 */

export type FoodCategory =
  | "protein"
  | "carbs"
  | "fats"
  | "vegetables"
  | "fruits"
  | "condiments"
  | "beverages"
  | "snacks";

export interface Food {
  slug: string;
  name: string;
  category: FoodCategory;
  /** human-readable common serving, e.g. "1 cup (158 g)" */
  serving: string;
  /** grams in that serving */
  grams: number;
  /** one practical coaching note */
  note: string;
  /** per 100 g */
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  /** exact USDA FoodData Central entry used */
  usdaName: string;
  /** FoodData Central ID, null where no USDA entry exists */
  fdcId: number | null;
}

export const CATEGORY_META: Record<
  FoodCategory,
  { label: string; blurb: string; index: string }
> = {
  protein: {
    label: "Protein",
    blurb: "Builds and repairs muscle. Anchor every meal here first.",
    index: "01",
  },
  carbs: {
    label: "Carbohydrates",
    blurb: "Fuels training. Put most of it around your session.",
    index: "02",
  },
  fats: {
    label: "Fats",
    blurb: "Hormones and absorption. Calorie dense, so measure it.",
    index: "03",
  },
  vegetables: {
    label: "Vegetables",
    blurb: "Volume, fibre and micronutrients for almost no calories.",
    index: "04",
  },
  fruits: {
    label: "Fruits",
    blurb: "Fast carbs with fibre. Whole fruit over juice, always.",
    index: "05",
  },
  condiments: {
    label: "Condiments",
    blurb: "Where hidden calories live. Flavour is cheap, sauce is not.",
    index: "06",
  },
  beverages: {
    label: "Beverages",
    blurb: "Drinks you forget to count. Liquid calories still count.",
    index: "07",
  },
  snacks: {
    label: "Snacks",
    blurb: "Planned, portioned, and accounted for. Not grazing.",
    index: "08",
  },
};

export const FOODS: Food[] = [
  {
    slug: "whey-protein-isolate",
    name: "Whey Protein Isolate",
    category: "protein",
    serving: "1 scoop (30 g)",
    grams: 30,
    note: "Convenience, not magic. Use it to fill gaps, not replace meals.",
    kcal: 376.7,
    protein: 83.3,
    carbs: 3.3,
    fat: 1.7,
    fiber: 0.0,
    usdaName: "Typical whey isolate label value (per 30 g scoop)",
    fdcId: null,
  },
  {
    slug: "chicken-breast",
    name: "Chicken Breast (raw)",
    category: "protein",
    serving: "1 breast (170 g)",
    grams: 170,
    note: "The default lean protein. Cheap per gram, endlessly versatile.",
    kcal: 120.0,
    protein: 22.5,
    carbs: 0.0,
    fat: 2.6,
    fiber: 0.0,
    usdaName: "Chicken, broiler or fryers, breast, skinless, boneless, meat only, raw",
    fdcId: 171077,
  },
  {
    slug: "sirloin-steak",
    name: "Sirloin Steak (raw)",
    category: "protein",
    serving: "6 oz (170 g)",
    grams: 170,
    note: "Lean cut. Rest it five minutes before slicing.",
    kcal: 131,
    protein: 22.1,
    carbs: 0.0,
    fat: 4.1,
    fiber: 0.0,
    usdaName: "Beef, top sirloin, steak, separable lean only, trimmed to 1/8\" fat, all grades, raw",
    fdcId: 174055,
  },
  {
    slug: "pork-tenderloin",
    name: "Pork Tenderloin (raw)",
    category: "protein",
    serving: "4 oz (113 g)",
    grams: 113,
    note: "As lean as chicken breast. Cook to 145°F and rest.",
    kcal: 109.0,
    protein: 21.0,
    carbs: 0.0,
    fat: 2.2,
    fiber: 0.0,
    usdaName: "Pork, fresh, loin, tenderloin, separable lean only, raw",
    fdcId: 168249,
  },
  {
    slug: "lean-ground-beef-93-7",
    name: "Lean Ground Beef 93/7",
    category: "protein",
    serving: "4 oz (113 g)",
    grams: 113,
    note: "Iron and creatine alongside the protein. Drain after browning.",
    kcal: 152,
    protein: 20.8,
    carbs: 0.0,
    fat: 7.0,
    fiber: 0.0,
    usdaName: "Beef, ground, 93% lean meat / 7% fat, raw",
    fdcId: 173110,
  },
  {
    slug: "salmon",
    name: "Salmon (raw)",
    category: "protein",
    serving: "1 fillet (170 g)",
    grams: 170,
    note: "Protein plus omega-3s. The fat here is the point.",
    kcal: 208.0,
    protein: 20.4,
    carbs: 0.0,
    fat: 13.4,
    fiber: 0.0,
    usdaName: "Fish, salmon, Atlantic, farmed, raw",
    fdcId: 175167,
  },
  {
    slug: "tempeh",
    name: "Tempeh",
    category: "protein",
    serving: "3 oz (85 g)",
    grams: 85,
    note: "Fermented and firmer than tofu. More protein per gram too.",
    kcal: 192.0,
    protein: 20.3,
    carbs: 7.6,
    fat: 10.8,
    fiber: 0,
    usdaName: "Tempeh",
    fdcId: 174272,
  },
  {
    slug: "tilapia",
    name: "Tilapia (raw)",
    category: "protein",
    serving: "1 fillet (113 g)",
    grams: 113,
    note: "Very lean, very mild. Takes on whatever you season it with.",
    kcal: 96.0,
    protein: 20.1,
    carbs: 0.0,
    fat: 1.7,
    fiber: 0.0,
    usdaName: "Fish, tilapia, raw",
    fdcId: 175176,
  },
  {
    slug: "shrimp",
    name: "Shrimp (raw)",
    category: "protein",
    serving: "4 oz (113 g)",
    grams: 113,
    note: "Cooks in three minutes. Almost pure protein.",
    kcal: 85.0,
    protein: 20.1,
    carbs: 0.0,
    fat: 0.5,
    fiber: 0,
    usdaName: "Crustaceans, shrimp, raw",
    fdcId: 175179,
  },
  {
    slug: "chicken-thigh",
    name: "Chicken Thigh (raw)",
    category: "protein",
    serving: "1 thigh (110 g)",
    grams: 110,
    note: "More fat and flavour than breast. Harder to overcook.",
    kcal: 121.0,
    protein: 19.7,
    carbs: 0.0,
    fat: 4.1,
    fiber: 0.0,
    usdaName: "Chicken, broilers or fryers, dark meat, thigh, meat only, raw",
    fdcId: 173627,
  },
  {
    slug: "canned-tuna-in-water",
    name: "Canned Tuna in Water",
    category: "protein",
    serving: "1 can (142 g)",
    grams: 142,
    note: "Shelf-stable protein for under a dollar. Keep some in your bag.",
    kcal: 90,
    protein: 19.0,
    carbs: 0.1,
    fat: 0.9,
    fiber: 0,
    usdaName: "Fish, tuna, light, canned in water, drained solids",
    fdcId: 334194,
  },
  {
    slug: "ground-turkey",
    name: "Ground Turkey (93/7)",
    category: "protein",
    serving: "4 oz (113 g)",
    grams: 113,
    note: "Swaps in for beef anywhere. Season it harder than you think.",
    kcal: 150,
    protein: 18.7,
    carbs: 0.0,
    fat: 8.3,
    fiber: 0.0,
    usdaName: "Turkey, ground, 93% lean, 7% fat, raw",
    fdcId: 172850,
  },
  {
    slug: "firm-tofu",
    name: "Firm Tofu",
    category: "protein",
    serving: "1/2 block (126 g)",
    grams: 126,
    note: "Press it dry before cooking or it will not brown.",
    kcal: 144.0,
    protein: 17.3,
    carbs: 2.8,
    fat: 8.7,
    fiber: 2.3,
    usdaName: "Tofu, raw, firm, prepared with calcium sulfate",
    fdcId: 172475,
  },
  {
    slug: "whole-egg",
    name: "Whole Egg",
    category: "protein",
    serving: "1 large egg (50 g)",
    grams: 50,
    note: "The whole food benchmark for protein quality.",
    kcal: 143.0,
    protein: 12.6,
    carbs: 0.7,
    fat: 9.5,
    fiber: 0.0,
    usdaName: "Egg, whole, raw, fresh",
    fdcId: 171287,
  },
  {
    slug: "cottage-cheese",
    name: "Cottage Cheese (lowfat 2%)",
    category: "protein",
    serving: "1 cup (226 g)",
    grams: 226,
    note: "Slow-digesting casein. Good before bed.",
    kcal: 84,
    protein: 11.0,
    carbs: 4.3,
    fat: 2.3,
    fiber: 0,
    usdaName: "Cheese, cottage, lowfat, 2% milkfat",
    fdcId: 328841,
  },
  {
    slug: "egg-white",
    name: "Egg White",
    category: "protein",
    serving: "1 white (33 g)",
    grams: 33,
    note: "Protein with the fat stripped out. Use alongside whole eggs.",
    kcal: 52.0,
    protein: 10.9,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0.0,
    usdaName: "Egg, white, raw, fresh",
    fdcId: 172183,
  },
  {
    slug: "greek-yogurt",
    name: "Greek Yogurt (plain, nonfat)",
    category: "protein",
    serving: "1 cup (227 g)",
    grams: 227,
    note: "High protein, low effort. Buy plain and add your own fruit.",
    kcal: 61,
    protein: 10.3,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    usdaName: "Yogurt, Greek, plain, nonfat",
    fdcId: 330137,
  },
  {
    slug: "lentils",
    name: "Lentils (cooked)",
    category: "protein",
    serving: "1 cup (198 g)",
    grams: 198,
    note: "Protein and fibre together. Cheapest protein in the shop.",
    kcal: 116.0,
    protein: 9.0,
    carbs: 20.1,
    fat: 0.4,
    fiber: 7.9,
    usdaName: "Lentils, mature seeds, cooked, boiled, without salt",
    fdcId: 172421,
  },
  {
    slug: "black-beans",
    name: "Black Beans (cooked)",
    category: "protein",
    serving: "1 cup (172 g)",
    grams: 172,
    note: "Rinse canned beans to cut the sodium roughly in half.",
    kcal: 132.0,
    protein: 8.9,
    carbs: 23.7,
    fat: 0.5,
    fiber: 8.7,
    usdaName: "Beans, black, mature seeds, cooked, boiled, without salt",
    fdcId: 173735,
  },
  {
    slug: "chickpeas",
    name: "Chickpeas (cooked)",
    category: "protein",
    serving: "1 cup (164 g)",
    grams: 164,
    note: "Roast them for a crunchy snack, blend them for hummus.",
    kcal: 164.0,
    protein: 8.9,
    carbs: 27.4,
    fat: 2.6,
    fiber: 7.6,
    usdaName: "Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt",
    fdcId: 173757,
  },
  {
    slug: "rolled-oats",
    name: "Rolled Oats (dry)",
    category: "carbs",
    serving: "1/2 cup dry (40 g)",
    grams: 40,
    note: "Weigh dry. Once cooked the volume triples and misleads you.",
    kcal: 379.0,
    protein: 13.2,
    carbs: 67.7,
    fat: 6.5,
    fiber: 10.1,
    usdaName: "Cereals, oats, regular and quick, not fortified, dry",
    fdcId: 173904,
  },
  {
    slug: "whole-wheat-bread",
    name: "Whole Wheat Bread",
    category: "carbs",
    serving: "1 slice (28 g)",
    grams: 28,
    note: "Check the label — the first ingredient should be whole grain.",
    kcal: 252.0,
    protein: 12.4,
    carbs: 42.7,
    fat: 3.5,
    fiber: 6.0,
    usdaName: "Bread, whole-wheat, commercially prepared",
    fdcId: 172688,
  },
  {
    slug: "bagel",
    name: "Bagel (plain)",
    category: "carbs",
    serving: "1 bagel (98 g)",
    grams: 98,
    note: "Dense carbs. One bagel equals roughly four slices of bread.",
    kcal: 264.0,
    protein: 10.6,
    carbs: 52.4,
    fat: 1.3,
    fiber: 1.6,
    usdaName: "Bagels, plain, enriched, with calcium propionate (includes onion, poppy, sesame)",
    fdcId: 174899,
  },
  {
    slug: "whole-wheat-pasta",
    name: "Whole Wheat Pasta (cooked)",
    category: "carbs",
    serving: "1 cup (140 g)",
    grams: 140,
    note: "More fibre and a firmer bite than white pasta.",
    kcal: 149.0,
    protein: 6.0,
    carbs: 30.1,
    fat: 1.7,
    fiber: 3.9,
    usdaName: "Pasta, whole-wheat, cooked (Includes foods for USDA's Food Distribution Program)",
    fdcId: 168910,
  },
  {
    slug: "pasta",
    name: "Pasta (cooked)",
    category: "carbs",
    serving: "1 cup (140 g)",
    grams: 140,
    note: "Cook it, cool it, eat it cold for more resistant starch.",
    kcal: 158,
    protein: 5.8,
    carbs: 30.9,
    fat: 0.9,
    fiber: 1.8,
    usdaName: "Pasta, cooked, enriched, without added salt",
    fdcId: 169737,
  },
  {
    slug: "corn-tortilla",
    name: "Corn Tortilla",
    category: "carbs",
    serving: "2 tortillas (52 g)",
    grams: 52,
    note: "Smaller and lower calorie than flour tortillas.",
    kcal: 218,
    protein: 5.7,
    carbs: 44.6,
    fat: 2.9,
    fiber: 6.3,
    usdaName: "Tortillas, ready-to-bake or -fry, corn",
    fdcId: 175036,
  },
  {
    slug: "quinoa",
    name: "Quinoa (cooked)",
    category: "carbs",
    serving: "1 cup (185 g)",
    grams: 185,
    note: "A complete protein as well as a carb. Rinse before cooking.",
    kcal: 120.0,
    protein: 4.4,
    carbs: 21.3,
    fat: 1.9,
    fiber: 2.8,
    usdaName: "Quinoa, cooked",
    fdcId: 168917,
  },
  {
    slug: "couscous",
    name: "Couscous (cooked)",
    category: "carbs",
    serving: "1 cup (157 g)",
    grams: 157,
    note: "Ready in five minutes with boiling water. No cooking needed.",
    kcal: 112.0,
    protein: 3.8,
    carbs: 23.2,
    fat: 0.2,
    fiber: 1.4,
    usdaName: "Couscous, cooked",
    fdcId: 169700,
  },
  {
    slug: "white-rice",
    name: "White Rice (cooked)",
    category: "carbs",
    serving: "1 cup (158 g)",
    grams: 158,
    note: "Easy to digest around training. Cook a batch for the week.",
    kcal: 130.0,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    usdaName: "Rice, white, long-grain, regular, unenriched, cooked without salt",
    fdcId: 169757,
  },
  {
    slug: "brown-rice",
    name: "Brown Rice (cooked)",
    category: "carbs",
    serving: "1 cup (195 g)",
    grams: 195,
    note: "More fibre than white. Takes twice as long to cook.",
    kcal: 123.0,
    protein: 2.7,
    carbs: 25.6,
    fat: 1.0,
    fiber: 1.6,
    usdaName: "Rice, brown, long-grain, cooked (Includes foods for USDA's Food Distribution Program)",
    fdcId: 169704,
  },
  {
    slug: "white-potato",
    name: "White Potato (raw)",
    category: "carbs",
    serving: "1 medium (173 g)",
    grams: 173,
    note: "Underrated. Very filling per calorie.",
    kcal: 95.0,
    protein: 2.6,
    carbs: 21.4,
    fat: 0.1,
    fiber: 2.3,
    usdaName: "Potatoes, Russet, flesh and skin, baked",
    fdcId: 170030,
  },
  {
    slug: "sweet-potato",
    name: "Sweet Potato (raw)",
    category: "carbs",
    serving: "1 medium (130 g)",
    grams: 130,
    note: "Roast whole at 200°C. Skin on for the fibre.",
    kcal: 86.0,
    protein: 1.6,
    carbs: 20.1,
    fat: 0.1,
    fiber: 3.0,
    usdaName: "Sweet potato, raw, unprepared (Includes foods for USDA's Food Distribution Program)",
    fdcId: 168482,
  },
  {
    slug: "cheddar-cheese",
    name: "Cheddar Cheese",
    category: "fats",
    serving: "1 oz (28 g)",
    grams: 28,
    note: "Mostly a fat source with useful protein attached.",
    kcal: 408,
    protein: 23.3,
    carbs: 2.4,
    fat: 34.0,
    fiber: 0,
    usdaName: "Cheese, cheddar",
    fdcId: 328637,
  },
  {
    slug: "peanut-butter",
    name: "Peanut Butter",
    category: "fats",
    serving: "2 tbsp (32 g)",
    grams: 32,
    note: "Buy the kind with two ingredients: peanuts and salt.",
    kcal: 598.0,
    protein: 22.2,
    carbs: 22.3,
    fat: 51.4,
    fiber: 5.0,
    usdaName: "Peanut butter, smooth style, without salt",
    fdcId: 172470,
  },
  {
    slug: "almonds",
    name: "Almonds",
    category: "fats",
    serving: "1 oz / 23 nuts (28 g)",
    grams: 28,
    note: "Count them out. Eating from the bag never ends well.",
    kcal: 579.0,
    protein: 21.2,
    carbs: 21.6,
    fat: 49.9,
    fiber: 12.5,
    usdaName: "Nuts, almonds",
    fdcId: 170567,
  },
  {
    slug: "ground-flaxseed",
    name: "Ground Flaxseed",
    category: "fats",
    serving: "2 tbsp (14 g)",
    grams: 14,
    note: "Must be ground to absorb it. Keep it in the fridge.",
    kcal: 534.0,
    protein: 18.3,
    carbs: 28.9,
    fat: 42.2,
    fiber: 27.3,
    usdaName: "Seeds, flaxseed",
    fdcId: 169414,
  },
  {
    slug: "cashews",
    name: "Cashews",
    category: "fats",
    serving: "1 oz (28 g)",
    grams: 28,
    note: "Higher in carbs than most nuts. Still calorie dense.",
    kcal: 553.0,
    protein: 18.2,
    carbs: 30.2,
    fat: 43.8,
    fiber: 3.3,
    usdaName: "Nuts, cashew nuts, raw",
    fdcId: 170162,
  },
  {
    slug: "chia-seeds",
    name: "Chia Seeds",
    category: "fats",
    serving: "2 tbsp (24 g)",
    grams: 24,
    note: "Absorbs ten times its weight in liquid. Great in overnight oats.",
    kcal: 486.0,
    protein: 16.5,
    carbs: 42.1,
    fat: 30.7,
    fiber: 34.4,
    usdaName: "Seeds, chia seeds, dried",
    fdcId: 170554,
  },
  {
    slug: "walnuts",
    name: "Walnuts",
    category: "fats",
    serving: "1 oz (28 g)",
    grams: 28,
    note: "The best plant source of omega-3 on this list.",
    kcal: 654.0,
    protein: 15.2,
    carbs: 13.7,
    fat: 65.2,
    fiber: 6.7,
    usdaName: "Nuts, walnuts, english",
    fdcId: 170187,
  },
  {
    slug: "avocado",
    name: "Avocado",
    category: "fats",
    serving: "1/2 avocado (68 g)",
    grams: 68,
    note: "Fat plus potassium and fibre. Calorie dense, so portion it.",
    kcal: 160.0,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    usdaName: "Avocados, raw, all commercial varieties",
    fdcId: 171705,
  },
  {
    slug: "butter",
    name: "Butter",
    category: "fats",
    serving: "1 tbsp (14 g)",
    grams: 14,
    note: "Almost pure fat. Cook with it, do not drown food in it.",
    kcal: 717.0,
    protein: 0.8,
    carbs: 0.1,
    fat: 81.1,
    fiber: 0.0,
    usdaName: "Butter, salted",
    fdcId: 173410,
  },
  {
    slug: "olive-oil",
    name: "Olive Oil",
    category: "fats",
    serving: "1 tbsp (14 g)",
    grams: 14,
    note: "Measure it. A free pour is easily triple what you intended.",
    kcal: 884.0,
    protein: 0.0,
    carbs: 0.0,
    fat: 100.0,
    fiber: 0.0,
    usdaName: "Oil, olive, salad or cooking",
    fdcId: 171413,
  },
  {
    slug: "coconut-oil",
    name: "Coconut Oil",
    category: "fats",
    serving: "1 tbsp (14 g)",
    grams: 14,
    note: "High smoke point. Nearly all saturated fat.",
    kcal: 892.0,
    protein: 0.0,
    carbs: 0.0,
    fat: 99.1,
    fiber: 0.0,
    usdaName: "Oil, coconut",
    fdcId: 171412,
  },
  {
    slug: "brussels-sprouts",
    name: "Brussels Sprouts (raw)",
    category: "vegetables",
    serving: "1 cup (88 g)",
    grams: 88,
    note: "Halve and roast cut-side down until charred.",
    kcal: 43.0,
    protein: 3.4,
    carbs: 8.9,
    fat: 0.3,
    fiber: 3.8,
    usdaName: "Brussels sprouts, raw",
    fdcId: 170383,
  },
  {
    slug: "mushrooms",
    name: "Mushrooms (raw)",
    category: "vegetables",
    serving: "1 cup sliced (70 g)",
    grams: 70,
    note: "Adds savoury depth. Dry-fry first to drive off water.",
    kcal: 22.0,
    protein: 3.1,
    carbs: 3.3,
    fat: 0.3,
    fiber: 1.0,
    usdaName: "Mushrooms, white, raw",
    fdcId: 169251,
  },
  {
    slug: "spinach",
    name: "Spinach (raw)",
    category: "vegetables",
    serving: "2 cups (60 g)",
    grams: 60,
    note: "Wilts to nothing, so use far more than looks right.",
    kcal: 23.0,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    usdaName: "Spinach, raw",
    fdcId: 168462,
  },
  {
    slug: "kale",
    name: "Kale (raw)",
    category: "vegetables",
    serving: "1 cup (67 g)",
    grams: 67,
    note: "Massage raw kale with oil and salt to soften it.",
    kcal: 35.0,
    protein: 2.9,
    carbs: 4.4,
    fat: 1.5,
    fiber: 4.1,
    usdaName: "Kale, raw",
    fdcId: 168421,
  },
  {
    slug: "broccoli",
    name: "Broccoli (raw)",
    category: "vegetables",
    serving: "1 cup chopped (91 g)",
    grams: 91,
    note: "Fills the plate for almost no calories. Roast, do not boil.",
    kcal: 34.0,
    protein: 2.8,
    carbs: 6.6,
    fat: 0.4,
    fiber: 2.6,
    usdaName: "Broccoli, raw",
    fdcId: 170379,
  },
  {
    slug: "asparagus",
    name: "Asparagus (raw)",
    category: "vegetables",
    serving: "6 spears (90 g)",
    grams: 90,
    note: "Roast at high heat for 12 minutes. Do not boil it.",
    kcal: 20.0,
    protein: 2.2,
    carbs: 3.9,
    fat: 0.1,
    fiber: 2.1,
    usdaName: "Asparagus, raw",
    fdcId: 168389,
  },
  {
    slug: "cauliflower",
    name: "Cauliflower (raw)",
    category: "vegetables",
    serving: "1 cup (107 g)",
    grams: 107,
    note: "Roast it, rice it, or mash it as a potato swap.",
    kcal: 25.0,
    protein: 1.9,
    carbs: 5.0,
    fat: 0.3,
    fiber: 2.0,
    usdaName: "Cauliflower, raw",
    fdcId: 169986,
  },
  {
    slug: "green-beans",
    name: "Green Beans (raw)",
    category: "vegetables",
    serving: "1 cup (100 g)",
    grams: 100,
    note: "Holds texture when reheated. Ideal for meal prep.",
    kcal: 31.0,
    protein: 1.8,
    carbs: 7.0,
    fat: 0.2,
    fiber: 2.7,
    usdaName: "Beans, snap, green, raw",
    fdcId: 169961,
  },
  {
    slug: "zucchini",
    name: "Zucchini (raw)",
    category: "vegetables",
    serving: "1 medium (196 g)",
    grams: 196,
    note: "Almost all water. Bulks out a meal for nearly nothing.",
    kcal: 17.0,
    protein: 1.2,
    carbs: 3.1,
    fat: 0.3,
    fiber: 1.0,
    usdaName: "Squash, summer, zucchini, includes skin, raw",
    fdcId: 169291,
  },
  {
    slug: "onion",
    name: "Onion (raw)",
    category: "vegetables",
    serving: "1/2 medium (55 g)",
    grams: 55,
    note: "The base of nearly every meal you will cook.",
    kcal: 40.0,
    protein: 1.1,
    carbs: 9.3,
    fat: 0.1,
    fiber: 1.7,
    usdaName: "Onions, raw",
    fdcId: 170000,
  },
  {
    slug: "bell-pepper",
    name: "Bell Pepper (raw)",
    category: "vegetables",
    serving: "1 medium (119 g)",
    grams: 119,
    note: "More vitamin C per gram than an orange.",
    kcal: 26.0,
    protein: 1.0,
    carbs: 6.0,
    fat: 0.3,
    fiber: 2.1,
    usdaName: "Peppers, sweet, red, raw",
    fdcId: 170108,
  },
  {
    slug: "carrots",
    name: "Carrots (raw)",
    category: "vegetables",
    serving: "1 medium (61 g)",
    grams: 61,
    note: "Keeps for weeks. Good crunch in a meal prep container.",
    kcal: 41.0,
    protein: 0.9,
    carbs: 9.6,
    fat: 0.2,
    fiber: 2.8,
    usdaName: "Carrots, raw",
    fdcId: 170393,
  },
  {
    slug: "tomato",
    name: "Tomato (raw)",
    category: "vegetables",
    serving: "1 medium (123 g)",
    grams: 123,
    note: "Cooking increases the available lycopene.",
    kcal: 18.0,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    usdaName: "Tomatoes, red, ripe, raw, year round average",
    fdcId: 170457,
  },
  {
    slug: "cucumber",
    name: "Cucumber (raw)",
    category: "vegetables",
    serving: "1/2 cucumber (150 g)",
    grams: 150,
    note: "Basically water with crunch. Free volume in a salad.",
    kcal: 15.0,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    usdaName: "Cucumber, with peel, raw",
    fdcId: 168409,
  },
  {
    slug: "dates",
    name: "Dates (Medjool)",
    category: "fruits",
    serving: "2 dates (48 g)",
    grams: 48,
    note: "Concentrated sugar. Useful pre-workout, easy to overdo.",
    kcal: 277.0,
    protein: 1.8,
    carbs: 75.0,
    fat: 0.1,
    fiber: 6.7,
    usdaName: "Dates, medjool",
    fdcId: 168191,
  },
  {
    slug: "raspberries",
    name: "Raspberries",
    category: "fruits",
    serving: "1 cup (123 g)",
    grams: 123,
    note: "Highest fibre per calorie of any fruit here.",
    kcal: 52.0,
    protein: 1.2,
    carbs: 11.9,
    fat: 0.7,
    fiber: 6.5,
    usdaName: "Raspberries, raw",
    fdcId: 167755,
  },
  {
    slug: "banana",
    name: "Banana",
    category: "fruits",
    serving: "1 medium (118 g)",
    grams: 118,
    note: "Portable carbs. Ideal 30 minutes before training.",
    kcal: 89.0,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    fiber: 2.6,
    usdaName: "Bananas, raw",
    fdcId: 173944,
  },
  {
    slug: "kiwi",
    name: "Kiwi",
    category: "fruits",
    serving: "2 kiwis (140 g)",
    grams: 140,
    note: "Eat the skin. It is edible and doubles the fibre.",
    kcal: 61.0,
    protein: 1.1,
    carbs: 14.7,
    fat: 0.5,
    fiber: 3.0,
    usdaName: "Kiwifruit, green, raw",
    fdcId: 168153,
  },
  {
    slug: "orange",
    name: "Orange",
    category: "fruits",
    serving: "1 medium (131 g)",
    grams: 131,
    note: "Eat it whole rather than juiced for the fibre.",
    kcal: 47.0,
    protein: 0.9,
    carbs: 11.8,
    fat: 0.1,
    fiber: 2.4,
    usdaName: "Oranges, raw, all commercial varieties",
    fdcId: 169097,
  },
  {
    slug: "mango",
    name: "Mango",
    category: "fruits",
    serving: "1 cup (165 g)",
    grams: 165,
    note: "Higher sugar. Works well post-training.",
    kcal: 60.0,
    protein: 0.8,
    carbs: 15.0,
    fat: 0.4,
    fiber: 1.6,
    usdaName: "Mangos, raw",
    fdcId: 169910,
  },
  {
    slug: "blueberries",
    name: "Blueberries",
    category: "fruits",
    serving: "1 cup (148 g)",
    grams: 148,
    note: "Buy frozen. Same nutrition, a fraction of the price.",
    kcal: 57.0,
    protein: 0.7,
    carbs: 14.5,
    fat: 0.3,
    fiber: 2.4,
    usdaName: "Blueberries, raw",
    fdcId: 171711,
  },
  {
    slug: "strawberries",
    name: "Strawberries",
    category: "fruits",
    serving: "1 cup (152 g)",
    grams: 152,
    note: "Lowest sugar of the common fruits.",
    kcal: 32.0,
    protein: 0.7,
    carbs: 7.7,
    fat: 0.3,
    fiber: 2.0,
    usdaName: "Strawberries, raw",
    fdcId: 167762,
  },
  {
    slug: "grapes",
    name: "Grapes",
    category: "fruits",
    serving: "1 cup (151 g)",
    grams: 151,
    note: "Easy to overeat. Freeze them to slow yourself down.",
    kcal: 67.0,
    protein: 0.6,
    carbs: 17.2,
    fat: 0.3,
    fiber: 0.9,
    usdaName: "Grapes, american type (slip skin), raw",
    fdcId: 174682,
  },
  {
    slug: "watermelon",
    name: "Watermelon",
    category: "fruits",
    serving: "1 cup (152 g)",
    grams: 152,
    note: "92% water. Enormous volume for very few calories.",
    kcal: 30.0,
    protein: 0.6,
    carbs: 7.5,
    fat: 0.1,
    fiber: 0.4,
    usdaName: "Watermelon, raw",
    fdcId: 167765,
  },
  {
    slug: "pineapple",
    name: "Pineapple",
    category: "fruits",
    serving: "1 cup (165 g)",
    grams: 165,
    note: "Contains bromelain, which is why it tingles.",
    kcal: 50.0,
    protein: 0.5,
    carbs: 13.1,
    fat: 0.1,
    fiber: 1.4,
    usdaName: "Pineapple, raw, all varieties",
    fdcId: 169124,
  },
  {
    slug: "apple",
    name: "Apple",
    category: "fruits",
    serving: "1 medium (182 g)",
    grams: 182,
    note: "Fibre and water make it far more filling than the calories suggest.",
    kcal: 52.0,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    fiber: 2.4,
    usdaName: "Apples, raw, with skin (Includes foods for USDA's Food Distribution Program)",
    fdcId: 171688,
  },
  {
    slug: "soy-sauce",
    name: "Soy Sauce",
    category: "condiments",
    serving: "1 tbsp (16 g)",
    grams: 16,
    note: "Watch the sodium, not the calories.",
    kcal: 53.0,
    protein: 8.1,
    carbs: 4.9,
    fat: 0.6,
    fiber: 0.8,
    usdaName: "Soy sauce made from soy and wheat (shoyu)",
    fdcId: 174277,
  },
  {
    slug: "yellow-mustard",
    name: "Yellow Mustard",
    category: "condiments",
    serving: "1 tsp (5 g)",
    grams: 5,
    note: "Essentially free calories. Use it generously.",
    kcal: 60,
    protein: 3.7,
    carbs: 5.8,
    fat: 3.3,
    fiber: 4.0,
    usdaName: "Mustard, prepared, yellow",
    fdcId: 172234,
  },
  {
    slug: "sriracha-hot-sauce",
    name: "Sriracha / Hot Sauce",
    category: "condiments",
    serving: "1 tsp (5 g)",
    grams: 5,
    note: "Near-zero calorie flavour. The dieter's best friend.",
    kcal: 93.0,
    protein: 1.9,
    carbs: 19.2,
    fat: 0.9,
    fiber: 2.2,
    usdaName: "Sauce, hot chile, sriracha",
    fdcId: 171186,
  },
  {
    slug: "salsa",
    name: "Salsa",
    category: "condiments",
    serving: "2 tbsp (36 g)",
    grams: 36,
    note: "A sauce that is actually just vegetables.",
    kcal: 29.0,
    protein: 1.4,
    carbs: 6.7,
    fat: 0.2,
    fiber: 1.8,
    usdaName: "Sauce, salsa, ready-to-serve",
    fdcId: 746777,
  },
  {
    slug: "ranch-dressing",
    name: "Ranch Dressing",
    category: "condiments",
    serving: "2 tbsp (29 g)",
    grams: 29,
    note: "Can add more calories than the chicken it is on.",
    kcal: 430.0,
    protein: 1.3,
    carbs: 5.9,
    fat: 44.5,
    fiber: 0.0,
    usdaName: "Salad dressing, ranch dressing, regular",
    fdcId: 173592,
  },
  {
    slug: "ketchup",
    name: "Ketchup",
    category: "condiments",
    serving: "1 tbsp (17 g)",
    grams: 17,
    note: "Mostly sugar. Fine in a tablespoon, not in a puddle.",
    kcal: 101.0,
    protein: 1.0,
    carbs: 27.4,
    fat: 0.1,
    fiber: 0.3,
    usdaName: "Catsup",
    fdcId: 168556,
  },
  {
    slug: "mayonnaise",
    name: "Mayonnaise",
    category: "condiments",
    serving: "1 tbsp (14 g)",
    grams: 14,
    note: "The most calorie-dense thing in your fridge. Measure it.",
    kcal: 680.0,
    protein: 1.0,
    carbs: 0.6,
    fat: 74.8,
    fiber: 0.0,
    usdaName: "Salad dressing, mayonnaise, regular",
    fdcId: 171009,
  },
  {
    slug: "bbq-sauce",
    name: "BBQ Sauce",
    category: "condiments",
    serving: "2 tbsp (36 g)",
    grams: 36,
    note: "Sugar first, flavour second. Read the label.",
    kcal: 172.0,
    protein: 0.8,
    carbs: 40.8,
    fat: 0.6,
    fiber: 0.9,
    usdaName: "Sauce, barbecue",
    fdcId: 174523,
  },
  {
    slug: "balsamic-vinegar",
    name: "Balsamic Vinegar",
    category: "condiments",
    serving: "1 tbsp (16 g)",
    grams: 16,
    note: "Big flavour, minimal calories. Reduce it for a glaze.",
    kcal: 88.0,
    protein: 0.5,
    carbs: 17.0,
    fat: 0.0,
    fiber: 0,
    usdaName: "Vinegar, balsamic",
    fdcId: 172241,
  },
  {
    slug: "honey",
    name: "Honey",
    category: "condiments",
    serving: "1 tbsp (21 g)",
    grams: 21,
    note: "Sugar with trace minerals. Treat it as sugar.",
    kcal: 304.0,
    protein: 0.3,
    carbs: 82.4,
    fat: 0.0,
    fiber: 0.2,
    usdaName: "Honey",
    fdcId: 169640,
  },
  {
    slug: "maple-syrup",
    name: "Maple Syrup",
    category: "condiments",
    serving: "1 tbsp (20 g)",
    grams: 20,
    note: "Real maple only. Pancake syrup is corn syrup.",
    kcal: 260.0,
    protein: 0.0,
    carbs: 67.0,
    fat: 0.1,
    fiber: 0.0,
    usdaName: "Syrups, maple",
    fdcId: 169661,
  },
  {
    slug: "skim-milk",
    name: "Skim Milk",
    category: "beverages",
    serving: "1 cup (245 g)",
    grams: 245,
    note: "Same protein as whole milk without the fat.",
    kcal: 34.0,
    protein: 3.4,
    carbs: 5.0,
    fat: 0.1,
    fiber: 0.0,
    usdaName: "Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)",
    fdcId: 171269,
  },
  {
    slug: "whole-milk",
    name: "Whole Milk",
    category: "beverages",
    serving: "1 cup (244 g)",
    grams: 244,
    note: "A drinkable protein source. Also easy to over-drink.",
    kcal: 61.0,
    protein: 3.1,
    carbs: 4.8,
    fat: 3.2,
    fiber: 0.0,
    usdaName: "Milk, whole, 3.25% milkfat, with added vitamin D",
    fdcId: 171265,
  },
  {
    slug: "orange-juice",
    name: "Orange Juice",
    category: "beverages",
    serving: "1 cup (248 g)",
    grams: 248,
    note: "The sugar of three oranges with none of the fibre.",
    kcal: 45.0,
    protein: 0.7,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.2,
    usdaName: "Orange juice, raw (Includes foods for USDA's Food Distribution Program)",
    fdcId: 169098,
  },
  {
    slug: "coconut-water",
    name: "Coconut Water",
    category: "beverages",
    serving: "1 cup (240 g)",
    grams: 240,
    note: "Potassium and light carbs. Not a sports drink replacement.",
    kcal: 19.0,
    protein: 0.7,
    carbs: 3.7,
    fat: 0.2,
    fiber: 1.1,
    usdaName: "Nuts, coconut water (liquid from coconuts)",
    fdcId: 170174,
  },
  {
    slug: "beer",
    name: "Beer (regular)",
    category: "beverages",
    serving: "1 can (356 g)",
    grams: 356,
    note: "Alcohol carries calories that macros do not capture.",
    kcal: 43,
    protein: 0.5,
    carbs: 3.5,
    fat: 0.0,
    fiber: 0.0,
    usdaName: "Alcoholic beverage, beer, regular, all",
    fdcId: 168746,
  },
  {
    slug: "almond-milk",
    name: "Almond Milk (unsweetened)",
    category: "beverages",
    serving: "1 cup (240 g)",
    grams: 240,
    note: "Almost no calories, but almost no protein either.",
    kcal: 15.0,
    protein: 0.4,
    carbs: 1.3,
    fat: 1.0,
    fiber: 0.2,
    usdaName: "Beverages, almond milk, unsweetened, shelf stable",
    fdcId: 174832,
  },
  {
    slug: "green-tea",
    name: "Green Tea (unsweetened)",
    category: "beverages",
    serving: "1 cup (245 g)",
    grams: 245,
    note: "Effectively zero calories. Good between meals.",
    kcal: 1.0,
    protein: 0.2,
    carbs: 0.0,
    fat: 0.0,
    fiber: 0.0,
    usdaName: "Beverages, tea, green, brewed, regular",
    fdcId: 171917,
  },
  {
    slug: "black-coffee",
    name: "Black Coffee",
    category: "beverages",
    serving: "1 cup (237 g)",
    grams: 237,
    note: "Free caffeine. It is what you add that costs you.",
    kcal: 1.0,
    protein: 0.1,
    carbs: 0.0,
    fat: 0.0,
    fiber: 0.0,
    usdaName: "Beverages, coffee, brewed, prepared with tap water",
    fdcId: 171890,
  },
  {
    slug: "diet-cola",
    name: "Diet Cola",
    category: "beverages",
    serving: "1 can (355 g)",
    grams: 355,
    note: "Zero calories. A useful bridge if you are cutting soda.",
    kcal: 1.0,
    protein: 0.1,
    carbs: 0.1,
    fat: 0.0,
    fiber: 0.0,
    usdaName: "Beverages, carbonated, low calorie, cola or pepper-type, with aspartame, without caffeine",
    fdcId: 174850,
  },
  {
    slug: "cola",
    name: "Cola",
    category: "beverages",
    serving: "1 can (368 g)",
    grams: 368,
    note: "Liquid sugar with no satiety. The easiest cut to make.",
    kcal: 42.0,
    protein: 0.0,
    carbs: 10.4,
    fat: 0.2,
    fiber: 0.0,
    usdaName: "Beverages, carbonated, cola, regular",
    fdcId: 174852,
  },
  {
    slug: "beef-jerky",
    name: "Beef Jerky",
    category: "snacks",
    serving: "1 oz (28 g)",
    grams: 28,
    note: "Protein that lives in your gym bag. High sodium.",
    kcal: 410.0,
    protein: 33.2,
    carbs: 11.0,
    fat: 25.6,
    fiber: 1.8,
    usdaName: "Snacks, beef jerky, chopped and formed",
    fdcId: 167536,
  },
  {
    slug: "string-cheese",
    name: "String Cheese (mozzarella)",
    category: "snacks",
    serving: "1 stick (28 g)",
    grams: 28,
    note: "Pre-portioned protein and fat. Hard to overeat.",
    kcal: 254.0,
    protein: 24.3,
    carbs: 2.8,
    fat: 15.9,
    fiber: 0.0,
    usdaName: "Cheese, mozzarella, part skim milk",
    fdcId: 170847,
  },
  {
    slug: "trail-mix",
    name: "Trail Mix",
    category: "snacks",
    serving: "1 oz (28 g)",
    grams: 28,
    note: "Calorie dense. Portion it out before you start.",
    kcal: 462.0,
    protein: 13.8,
    carbs: 44.9,
    fat: 29.4,
    fiber: 0,
    usdaName: "Snacks, trail mix, regular",
    fdcId: 167561,
  },
  {
    slug: "popcorn",
    name: "Popcorn (air-popped)",
    category: "snacks",
    serving: "3 cups (24 g)",
    grams: 24,
    note: "Huge volume for the calories. Air-popped, not cinema.",
    kcal: 387.0,
    protein: 12.9,
    carbs: 77.8,
    fat: 4.5,
    fiber: 14.5,
    usdaName: "Snacks, popcorn, air-popped",
    fdcId: 167959,
  },
  {
    slug: "granola-bar",
    name: "Granola Bar",
    category: "snacks",
    serving: "1 bar (28 g)",
    grams: 28,
    note: "Often a biscuit in disguise. Check the sugar.",
    kcal: 471.0,
    protein: 10.1,
    carbs: 64.4,
    fat: 19.8,
    fiber: 5.3,
    usdaName: "Snacks, granola bars, hard, plain",
    fdcId: 167542,
  },
  {
    slug: "pretzels",
    name: "Pretzels",
    category: "snacks",
    serving: "1 oz (28 g)",
    grams: 28,
    note: "Low fat but low satiety. Easy to keep eating.",
    kcal: 384.0,
    protein: 10.0,
    carbs: 80.4,
    fat: 2.9,
    fiber: 3.4,
    usdaName: "Snacks, pretzels, hard, plain, salted",
    fdcId: 167555,
  },
  {
    slug: "rice-cakes",
    name: "Rice Cakes",
    category: "snacks",
    serving: "2 cakes (18 g)",
    grams: 18,
    note: "A vehicle for toppings rather than a food itself.",
    kcal: 387.0,
    protein: 8.2,
    carbs: 81.5,
    fat: 2.8,
    fiber: 4.2,
    usdaName: "Snacks, rice cakes, brown rice, plain, unsalted",
    fdcId: 170250,
  },
  {
    slug: "dark-chocolate",
    name: "Dark Chocolate (70-85%)",
    category: "snacks",
    serving: "1 oz (28 g)",
    grams: 28,
    note: "A square or two satisfies. The bar does not.",
    kcal: 598.0,
    protein: 7.8,
    carbs: 45.9,
    fat: 42.6,
    fiber: 10.9,
    usdaName: "Chocolate, dark, 70-85% cacao solids",
    fdcId: 170273,
  },
  {
    slug: "hummus",
    name: "Hummus",
    category: "snacks",
    serving: "2 tbsp (30 g)",
    grams: 30,
    note: "Protein and fibre in a dip. Pair with vegetables.",
    kcal: 237.0,
    protein: 7.8,
    carbs: 15.0,
    fat: 17.8,
    fiber: 5.5,
    usdaName: "Hummus, commercial",
    fdcId: 174289,
  },
  {
    slug: "potato-chips",
    name: "Potato Chips",
    category: "snacks",
    serving: "1 oz (28 g)",
    grams: 28,
    note: "An ounce is about 15 chips. Nobody eats 15 chips.",
    kcal: 532.0,
    protein: 6.4,
    carbs: 53.8,
    fat: 34.0,
    fiber: 3.1,
    usdaName: "Snacks, potato chips, plain, salted",
    fdcId: 169677,
  },
];

/* ── helpers ─────────────────────────────────────────────────────── */

/** Macros for an arbitrary gram amount of a food. */
export function scale(food: Food, grams: number) {
  const f = grams / 100;
  return {
    kcal: food.kcal * f,
    protein: food.protein * f,
    carbs: food.carbs * f,
    fat: food.fat * f,
    fiber: food.fiber * f,
  };
}

/** Macros for one standard serving of a food. */
export function perServing(food: Food) {
  return scale(food, food.grams);
}

export function getFood(slug: string): Food | null {
  return FOODS.find((f) => f.slug === slug) ?? null;
}

export function byCategory(category: FoodCategory): Food[] {
  return FOODS.filter((f) => f.category === category);
}

/** Share of calories from each macro, for the breakdown bars. */
export function macroSplit(m: {
  protein: number;
  carbs: number;
  fat: number;
}) {
  const p = m.protein * 4;
  const c = m.carbs * 4;
  const f = m.fat * 9;
  const total = p + c + f;
  if (total <= 0) return { protein: 0, carbs: 0, fat: 0 };
  return {
    protein: (p / total) * 100,
    carbs: (c / total) * 100,
    fat: (f / total) * 100,
  };
}
