import express from "express";
import { createServer } from "http";
import { readFile } from "node:fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

type RouteManifest = {
  snapshotRoutes: Record<string, string>;
  appRoutes: string[];
  guideSlugs: string[];
};

function normalizePathname(value: string) {
  if (value === "/") return value;
  return value.replace(/\/+$/, "") || "/";
}

async function loadRouteManifest(staticPath: string): Promise<RouteManifest> {
  const source = await readFile(
    path.join(staticPath, "route-manifest.json"),
    "utf8"
  );
  const manifest = JSON.parse(source) as Partial<RouteManifest>;
  if (
    !manifest.snapshotRoutes ||
    !Array.isArray(manifest.appRoutes) ||
    !Array.isArray(manifest.guideSlugs)
  ) {
    throw new Error(
      "Invalid route-manifest.json generated by the discovery build."
    );
  }
  return {
    snapshotRoutes: manifest.snapshotRoutes,
    appRoutes: manifest.appRoutes,
    guideSlugs: manifest.guideSlugs,
  };
}

function sendNotFound(res: express.Response, staticPath: string) {
  res.set("X-Robots-Tag", "noindex, nofollow");
  res.status(404).sendFile(path.join(staticPath, "404.html"), error => {
    if (error && !res.headersSent) {
      res.status(404).type("text/plain").send("Not found");
    }
  });
}

export async function createApp(staticPath: string) {
  const manifest = await loadRouteManifest(staticPath);
  const app = express();
  const appRoutes = new Set(manifest.appRoutes.map(normalizePathname));
  const guideSlugs = new Set(manifest.guideSlugs);
  const snapshots = new Map(
    Object.entries(manifest.snapshotRoutes).map(([route, file]) => [
      normalizePathname(route),
      file,
    ])
  );

  // Files produced by Vite and the public crawler artifacts retain ordinary
  // static behavior. A missing asset falls through and receives a true 404.
  app.use(express.static(staticPath, { index: false, fallthrough: true }));

  app.get("/e/:slug", (req, res) => {
    const slug = req.params.slug;
    if (!guideSlugs.has(slug)) return sendNotFound(res, staticPath);
    return res.sendFile(path.join(staticPath, "guides", `${slug}.html`));
  });

  app.get("*", (req, res) => {
    const route = normalizePathname(req.path);
    const snapshot = snapshots.get(route);
    if (snapshot) return res.sendFile(path.join(staticPath, snapshot));

    if (route === "/404") return sendNotFound(res, staticPath);
    if (appRoutes.has(route)) {
      return res.sendFile(path.join(staticPath, "app.html"));
    }

    return sendNotFound(res, staticPath);
  });

  return app;
}

async function startServer() {
  const staticPath =
    process.env.NODE_ENV === "production"
      ? path.resolve(__dirname, "public")
      : path.resolve(__dirname, "..", "dist", "public");
  const app = await createApp(staticPath);
  const server = createServer(app);
  const port = Number(process.env.PORT || 3000);

  server.listen(port, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${port}/`);
  });
}

if (process.env.VITEST !== "true") {
  startServer().catch(error => {
    console.error(error);
    process.exitCode = 1;
  });
}
